name: CI
on:
  pull_request:
  push:
    branches:
      - feature/**
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [x86, x64]
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git fetch --prune --unshallow
          git ls-tree HEAD vendor/fmt vendor/libtorrent vendor/loguru vendor/nlohmann-json vendor/sentry-crashpad vendor/wx > .vendor-status

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            build-${{ matrix.arch }}
            !build-${{ matrix.arch }}/PicoTorrent-coredb.dir
            !build-${{ matrix.arch }}/PicoTorrent.dir
            !build-${{ matrix.arch }}/Plugin_Filters.dir
            !build-${{ matrix.arch }}/Plugin_Updater.dir
            !build-${{ matrix.arch }}/Release
            !build-${{ matrix.arch }}/CMakeCache.txt
          key: ${{ runner.os }}-${{ matrix.arch }}-${{ hashFiles('.vendor-status') }}

      - name: Prepare
        run: |
          git submodule update --init --recursive
  
      - name: Install dependencies
        run: |
          if ('${{ matrix.arch }}' -eq 'x64') {
            choco install openssl --no-progress
          } elseif ('${{ matrix.arch }}' -eq 'x86') {
            choco install openssl --no-progress --x86
          }

          dotnet tool restore

      - name: Set environment variables
        run: |
          echo "BOOST_ROOT=$env:BOOST_ROOT_1_72_0" >> $GITHUB_ENV
          if ('${{ matrix.arch }}' -eq 'x64') {
            echo "OPENSSL_ROOT_DIR=$env:ProgramFiles\OpenSSL-Win64" >> $GITHUB_ENV
          } elseif ('${{ matrix.arch }}' -eq 'x86') {
            echo "OPENSSL_ROOT_DIR=${env:ProgramFiles(x86)}\OpenSSL-Win32" >> $GITHUB_ENV
          }

      - name: Build
        run: dotnet cake --platform=${{ matrix.arch }} --target=Publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PicoTorrent-${{ matrix.arch }}-CI-binaries
          path: |
            build-${{ matrix.arch }}/Release/packages/PicoTorrent-*-${{ matrix.arch }}.exe
            build-${{ matrix.arch }}/Release/packages/PicoTorrent-*-${{ matrix.arch }}.zip
            build-${{ matrix.arch }}/Release/packages/PicoTorrent-*-${{ matrix.arch }}.symbols.zip
